version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    region: digitalocean-ams3
    regionendpoint: ams3.digitaloceanspaces.com
    bucket: SPACE_NAME
    accesskey: ACCESS_KEY
    secretkey: SECRET_KEY
  delete:
    enabled: true
http:
  addr: :5000
  host: https://sub.example.com
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: https://sub.example.com
    path: /etc/nginx/.htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

